### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [kenortiz/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kenortiz** [comment]
Thanks for the feedback Ken.

I added the viewport meta tag, in between the <head> tags, in the application.html.erb file. 

``` html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

I also double-checked the mobile view on my phone by using my phone's browser and going to "computer_ip:3030".

The viewport meta tag will now allow browsers to render the width of the page based on its screen.

**Comment by kenmazaika** [comment]
You got it, Kenneth!  Thumbs up on adding that line!
